/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.tomtom.places.unicorn.domain.avro.tracer;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface PlaceTraceDefinition {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"PlaceTraceDefinition\",\"namespace\":\"com.tomtom.places.unicorn.domain.avro.tracer\",\"types\":[{\"type\":\"record\",\"name\":\"NormalizedPlace\",\"namespace\":\"com.tomtom.places.unicorn.domain.avro.normalized\",\"fields\":[]},{\"type\":\"record\",\"name\":\"ClusteredPlace\",\"namespace\":\"com.tomtom.places.unicorn.domain.avro.clustered\",\"fields\":[]},{\"type\":\"record\",\"name\":\"ArchivePlace\",\"namespace\":\"com.tomtom.places.unicorn.domain.avro.archive\",\"fields\":[]},{\"type\":\"record\",\"name\":\"Trace\",\"namespace\":\"com.tomtom.places.unicorn.domain.avro.trace\",\"fields\":[]},{\"type\":\"record\",\"name\":\"PlaceTrace\",\"fields\":[{\"name\":\"mappedPlace\",\"type\":[\"null\",\"com.tomtom.places.unicorn.domain.avro.normalized.NormalizedPlace\"],\"default\":null},{\"name\":\"clusteredPlace\",\"type\":[\"null\",\"com.tomtom.places.unicorn.domain.avro.clustered.ClusteredPlace\"],\"default\":null},{\"name\":\"archivePlace\",\"type\":[\"null\",\"com.tomtom.places.unicorn.domain.avro.archive.ArchivePlace\"],\"default\":null},{\"name\":\"traces\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"com.tomtom.places.unicorn.domain.avro.trace.Trace\"}],\"default\":null}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends PlaceTraceDefinition {
    public static final org.apache.avro.Protocol PROTOCOL = com.tomtom.places.unicorn.domain.avro.tracer.PlaceTraceDefinition.PROTOCOL;
  }
}